### ISSUE TITLE
multi-file binary baton-get?

### ISSUE THREAD

**Issue by mcast** [wtsi-npg/baton#110]
Hi again,

For fetching large files to disk, it seems `iget` is still the tool to use - overhead will be negligible and it may parallelise when appropriate - but only if I want the whole thing.

So I'm looking at how to fetch a number of small files, or maybe parts of a large one.

1. I can `--save` to disk and keep it as cache, but I'm looking for alternatives.
2. I can `--raw`,
  * Could the JSON request be extended to accept a byterange?
  * Is it safe to stream multiple files with raw and cut them up by a bytecount?
  * Is there some IPC standard for multiple files on STDOUT?  Other than `.tar` emulation, which seems a little heavy on both sides.
  * How do I separate from the data any JSON error object which could occur mid-file?  Are there guarantees about when this would arrive?  Would it be appropriate to use another filehandle?  It seems complicated to have to keep some data back and search its tail for the message iff the exit code is non-zero.
3. If I'm sure they are text I can get them as JSON, but...  I can't guarantee that.
  * Is exclusion of binaries due to CPU overhead of quoting characters?
4. Would it suit your interface style to send the bytecount before each raw data block?
  * as uint8 or a BER-like extendable binary number scheme
  * alternating json_object_text_header / raw_data / ...
5. Can I stream requests to STDIN while streaming the responses from STDOUT?

While benchmarking, I'm requesting sizes separately with a separate `baton-list --size`, (skipping the very big ones to save time) and seeing about 23 MiB/sec + 0.8 sec latency.  Underlying storage is NFS via `ireg`, and provides ~100MiB/sec + 10ms latency.

Sorry to be vague, I'm not sure whether I want advice or new features.

**Comment by mcast** [comment]
Summarising things Keith told me just now,
* `--unbuffered` flushes after each JSON object out, to support streaming of text files.
* Mixing JSON and raw data on STDOUT goes against the design philosophy.  It should be possible to pipe the JSON output into `jq` or something else.
* We didn't discover or specify an IPC standard for multiple files on STDOUT.
* Recommendation for [Perf](https://perf.wiki.kernel.org/index.php/Main_Page) to see what is causing slowness.
* Suggestion that specific problems like presenting iRODS files by HTTP might be best solved by writing a new tool against the C API.
* We didn't get a good idea of "what the performance should be like" for read/write access to iRODS on any particular hardware.
* Baton doesn't parallelise data fetches the way `iget` can for larger files.

After we finished talking, I remembered [BERT](http://bert-rpc.org/); also compare [BSON](https://en.wikipedia.org/wiki/BSON) and [MsgPack](http://msgpack.org/).
* They provide the middle ground of
  * Structured data, which will map well enough to JSON for this application
  * Efficient handling of binary strings
* But would be quite a change for Baton,
  * isolating it from `jq` and other tools
  * not human readable or terminal-friendly until translated.


We concluded that Baton isn't what I need at this point, because I need a POSIX filesystem emulation.

**Comment by keithj** [comment]
Thanks for the feedback. If you have any more ideas or comments, please re-open (or open a new issue).
