### ISSUE TITLE
iRODS header file name renaming

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/baton#116]
3.3.1 C API has `*.h` headers
4.0-4.0.3 C API renamed to `*.hpp` headers
4.1.0+ C API renamed to `*.h` headers

See irods/irods#2648 and https://github.com/irods/irods/commit/00b78660acbccbe78fa2c319a0a47c552334d8fd

To continue support for 4.0.x will require new autoconf sections to distinguish between 4.0.x  and 4.1.x and updating of relevant baton headers.

**Comment by tempoz** [comment]
Notably, though, the hpp headers will remain in place as links in the irods-dev package.

**Comment by keithj** [comment]
Fixed by f07e9cbaad0327854631abeb928523ba77b19f77
