### ISSUE TITLE
baton-metaquery outputs invalid json for long-running queries using iRODS 3.x

### ISSUE THREAD

**Issue by jrandall** [wtsi-npg/baton#144]
When `baton-metaquery` runs for a very long time, stdout ends up with messages from iRODS (v3.x) printed to stdout before the json starts, which obviously breaks parsing.

For example, a recent run of `baton-metaquery` resulted in stdout that started like this:
```
The client/server socket connection has been renewed
The client/server socket connection has been renewed
The client/server socket connection has been renewed
[{"data_object": "14861_5#1.cram", "collection": "/seq/14861", 
```

The offending code in iRODS is: https://github.com/irods/irods/blob/3.0/iRODS/lib/core/src/sockComm.c#L1501

iRODS v4.x has since fixed this (https://github.com/irods/irods/blob/4-0-stable/iRODS/lib/core/src/sockComm.cpp#L1571-L1572) but in the meantime it would be nice to have a workaround for baton. 

Some options: 
 - add an option to baton to output to a file rather than STDOUT, so that iRODS STDOUT spew doens't interfere with our output
 - run all iRODS calls in a subprocess or thread with I/O redirected (i.e. so you can catch STDOUT from iRODS and reprint it on STDERR where it belongs)

**Comment by keithj** [comment]
The WTSI iRODS is patched to avoid this. Certainly, we don't see it on production.

**Comment by keithj** [comment]
Unless you have strong objections, I'll close the subprocess option this as `wontfix` because it's really an iRODS bug and I'll keep the output to a file option as an enhancement.
