### ISSUE TITLE
Segfaults on specific query tests

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/baton#149]
Not happening on Travis, but happening everywhere else!

````
check_baton.c:1907:E:basic:test_make_query_format_from_sql_with_simple_select_query:0: (after this point) Received signal 11 (Segmentation fault)
check_baton.c:1922:E:basic:test_make_query_format_from_sql_with_select_query_using_column_alias:0: (after this point) Received signal 11 (Segmentation fault)
check_baton.c:1942:P:basic:test_make_query_format_from_sql_with_invalid_query:0: Passed
check_baton.c:1964:E:basic:test_search_specific_with_valid_setup:0: (after this point) Received signal 11 (Segmentation fault)
````

**Comment by jrandall** [comment]
Not sure how to debug this as it is working in Travis and we don't have any other environment in which to test. I'll add some guards against NULL pointer dereferences and maybe then you'll get more useful errors out of the tests.

**Comment by keithj** [comment]
I've added regex error messages and the offending tests report this on Ubuntu Trusty:

`
2016-03-31T13:19:01 ERROR Could not compile regex: '^.*?select[[:space:]]+(distinct|all[[:space:]]+)?(.*?[^[:space:]])[[:space:]]+from[[:space:]].*$': Invalid preceding regular expression prior to repetition operator.
`

**Comment by jrandall** [comment]
Mysterious. I have tested compiling this regex in an Ubuntu Trusty docker container and it works fine. Can you try this test code on your machine:
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <regex.h>


int main() {
  int reti;
  char regex_err[1024];
  const char *test_re_str =
    "^.*?select[[:space:]]+"
    "(distinct|all[[:space:]]+)?(.*?[^[:space:]])[[:space:]]+"
    "from[[:space:]].*$";
  regex_t test_re;
  reti = regcomp(&test_re, test_re_str, REG_EXTENDED | REG_ICASE);
  if (reti != 0) {
    regerror(reti, &test_re, &regex_err, 1024);
    printf("regcomp failed: %s\n", reti, regex_err);
    exit(1);
  }
  exit(0);
}
```

**Comment by jrandall** [comment]
Mysterious. I have tested compiling this regex in an Ubuntu Trusty docker container and it works fine. Can you try this test code on your machine:
```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <regex.h>


int main() {
  int reti;
  char regex_err_buf[1024];
  char *errbuf = regex_err_buf;
  const char *test_re_str =
    "^.*?select[[:space:]]+"
    "(distinct|all[[:space:]]+)?(.*?[^[:space:]])[[:space:]]+"
    "from[[:space:]].*$";
  regex_t test_re;
  reti = regcomp(&test_re, test_re_str, REG_EXTENDED | REG_ICASE);
  if (reti != 0) {
    regerror(reti, &test_re, errbuf, 1024);
    printf("regcomp failed: %s\n", errbuf);
    exit(1);
  }
  exit(0);
}
```

**Comment by jrandall** [comment]
I tested on: 
```
root@8befc2bb5a6b:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
root@8befc2bb5a6b:/# gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
and it exited 0 with no errors

**Comment by keithj** [comment]
I have here the same:

````
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

Your test program compiles the regex successfully for me too. However, the same regex *in situ* in `query.c` gives the error.

**Comment by keithj** [comment]
Aha, but if I add that test program to the autotools build and then run it, I get the error message.

**Comment by jrandall** [comment]
Huh. It looks like Boost has a POSIX compatibility mode that appears to be identical to the system regex.h: http://www.boost.org/doc/libs/1_34_0/libs/regex/doc/posix_api.html

Maybe the problem is that baton is using `-lboost_regex` which contains the compatibility symbols, but we are including `<regex.h>` instead of `<boost/regex.h>`. Could you try changing to the latter?

**Comment by keithj** [comment]
The boost POSIX compatibility mode appears not to be compatible in this respect! I've disocvered that including `<regex.h>` was actually picking up `<boost/regex.h>` because of the way I had set the path to the boost headers for RIP (I have to hackily point into the uninstalled boost build directory in iRODS' `external` directory.) Once I've set the path so that  `<regex.h>` only matches the `libc` version then we are okay.
