### ISSUE TITLE
`baton-chmod` does not provide a descriptive error message if used to modify a non-existent entity

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-npg/baton#155]
It would be helpful if baton gave a more descriptive error message in the JSON it returns when `baton-chmod` is used to alter the permissions of an entity that does not exist. Useful information is spit out into stderr but fails to make it into the JSON representation, which instead includes a rather vague failure message:

```
$ jq -n '{"collection": "/Sanger1/home/cn13/non_existent", "access": [{"owner": "cn13", "zone": "Sanger1", "level": "read"}]}' | baton-chmod
2016-04-11T15:11:48 WARN Failed to stat iRODS path '/Sanger1/home/cn13/non_existent'.
2016-04-11T15:11:48 ERROR Failed to modify permissions of '/Sanger1/home/cn13/non_existent' to 'read' for 'cn13'.
2016-04-11T15:11:48 ERROR Level 0: Input path is not a collection and not a dataObj: /Sanger1/home/cn13/non_existent.
{"access": [{"level": "read", "zone": "Sanger1", "owner": "cn13"}], "collection": "/Sanger1/home/cn13/non_existent", "error": {"message": "Failed to modify permissions of '/Sanger1/home/cn13/non_existent' to 'read' for 'cn13'", "code": -816000}}
```

**Comment by keithj** [comment]
To resolve this we'd have to do an extra check ourselves (another round-trip) to check the existence of the thing first. I think that the real issue here is iRODS' error message being too generic and this this should be fixed there instead.
