### ISSUE TITLE
irods 4.2.2 compatibility

### ISSUE THREAD

**Issue by kuntzagk** [wtsi-npg/baton#201]
Hi,

is it planned to make baton build agains irods 4.2.2?

regards, Andreas

**Comment by keithj** [comment]
Yes, it is. There is a pull request #198 which fails to build for me on Ubuntu Xenial (although it passes Travis test). We're using iRODS 4.1.11 locally, so I haven't merged it yet.

**Comment by kjsanger** [comment]
#198 superseded by #208, awaiting review and merge.
