### ISSUE TITLE
baton does not parse 0 as a command line argument value

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-npg/baton#212]
If you specify a command line argument value of `0` to any option that makes sense, `baton` does not parse it:

    $ baton -c 0
    {"avus":[]}
    $ baton -d 0
    {"avus":[]}
    $ baton -f 0
    {"avus":[]}
    $ baton -c /some/collection -d 0
    {"avus":[],"collection":"/some/collection"}
    # etc.

This came up because of a data object named `0`. Strictly numeric values other than zero do appear to work. I haven't tried all combinations of arguments, but the above are definitely affected.

**Comment by kjsanger** [comment]
As the `baton` executable is just a Perl script, I suspect some Perl truthiness issue. Yes:

https://github.com/wtsi-npg/baton/blob/devel/src/baton.in#L69
