### ISSUE TITLE
Memory error when attempting to get the checksum for some files

### ISSUE THREAD

**Issue by Xophmeister** [wtsi-npg/baton#239]
`baton-list --checksum` is aborting with the following error for _some_ files:

    munmap_chunk(): invalid pointer
    Aborted (core dumped)

It's not clear what conditions cause this to happen. Here's an example file that causes the problem:

    /seq/illumina/library_merge/16261230.HXV2.paired308.edec547d03/16261230.HXV2.paired308.edec547d03.cram

`ils -L` on this file shows that the checksum is there.

(v2.0.1-10-g1da6bc5-dirty)

**Comment by kjsanger** [comment]
The checksum is only there on one replicate, which is triggering the error. Probably was fixed by #230

**Comment by kjsanger** [comment]
We're trying to push through a 3.0.0 release which will contain this fix.
