### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by muffato** [wtsi-npg/baton#257]
Hello,

I faced a few issues when trying to install baton on a fresh Ubuntu 18.04 container:

 - Some Perl dependencies (for `baton`) are not declared in `README` or `INSTALL`: `FindBin`, `JSON`, `List::AllUtils`
 - After `make install`, the binaries installed in `/usr/local/bin` were not able to find the .so, and I had to run an additional `ldconfig /usr/local/lib/`. I noticed that `make install` already runs `ldconfig`, but with the `-n` option. I think the problem is the same as https://github.com/esnet/iperf/issues/153#issuecomment-42897883

Best,
Matthieu

**Comment by kjsanger** [comment]
Closed with a workaround of running ldconfig separately (this is what we do e.g. in Dockerfiles). Folding it into the Makefile affects non-root users
